FileStorage:
  class: Pantono\Storage\FileStorage
FileSystem:
  class: Pantono\Storage\Factory\FileSystemFactory
  aliases:
    - League\Flysystem\Filesystem
  parameters:
    - $filesystem.dsn
    - "@Logger"
    - $filesystem.adapter_options
    - $filesystem.options
